### ISSUE TITLE
Missing momentum2.mps.gz file

### ISSUE THREAD

**Issue by smoretti** [biosustain/optlang#167]
Hi

I got an error when running *python2 setup.py test*:
```
ERROR: Failure: IOError ([Errno 2] No such file or directory: '/builddir/build/BUILD/optlang-1.4.2/slow_tests/data/miplib2003/momentum2.mps.gz')
```

python2 version 2.7.12

**Comment by KristianJensen** [comment]
Hi. Thanks for the report. Do you get a longer traceback, or just this line?

**Comment by smoretti** [comment]
Here is the traceback:
```
ERROR: Failure: IOError ([Errno 2] No such file or directory: '/builddir/build/BUILD/optlang-1.4.2/slow_tests/data/miplib2003/momentum2.mps.gz')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/builddir/build/BUILD/optlang-1.4.2/slow_tests/test_miplib_glpk_interface.py", line 74, in test_miplib
    glpk_problem, model = load_problem(problem_file)
  File "/builddir/build/BUILD/optlang-1.4.2/slow_tests/test_miplib_glpk_interface.py", line 39, in load_problem
    f = gzip.open(mps_file, 'rb')
  File "/software/lib64/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/software/lib64/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 2] No such file or directory: '/builddir/build/BUILD/optlang-1.4.2/slow_tests/data/miplib2003/momentum2.mps.gz'
----------------------------------------------------------------------
```

**Comment by smoretti** [comment]
With python 2.7.12 and glpk 4.59 I have also this error during tests (not with python3):
```
ERROR: Failure: Exception (No optimal solution found for netlib model SIERRA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/lib/python2.7/site-packages/nose/loader.py", line 251, in generate
    for test in g():
  File "/builddir/build/BUILD/optlang-1.4.2/optlang/tests/test_netlib_glpk_exact_interface.py", line 91, in test_netlib
    raise Exception('No optimal solution found for netlib model %s' % netlib_id)
Exception: No optimal solution found for netlib model SIERRA
```

**Comment by KristianJensen** [comment]
Thanks. We will look into it. There are currently some problems with our miplib tests, but if all the other tests pass everything should be in order.

If you encounter the missing file error, you can try running the tests with `nosetests optlang` instead

**Comment by smoretti** [comment]
OK, thanks
`nosetests optlang` skips the file error test.

Only my "No optimal solution found for netlib model SIERRA" remains

**Comment by smoretti** [comment]
I have excluded the netlib model **SIERRA** to skip it, and after that for Python 2 I got errors for the netlib model **WOOD1P**.

Skipping both let me complete tests successfully.
