### ISSUE TITLE
Attempting to import optlang.inspyred_interface causes error

### ISSUE THREAD

**Issue by DManowitz** [biosustain/optlang#250]
#### Problem description
Attempting to import optlang.inspyred_interface causes error.  This should be importable.  I think the call to `import interface` should be `from optlang import interface`, as done in other _interface files.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```
import optlang.inspyred_interface
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\lib\site-packages\optlang\inspyred_interface.py", line 29, in <module>
    import interface
ModuleNotFoundError: No module named 'interface'
```

### Context

<details>

```
>>> optlang.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'optlang' has no attribute 'show_versions'
```

</details>

**Comment by cdiener** [comment]
That interface has not been update for three years and the inspired package itself looks abandoned so I would suspect it wouldn't even work with the correct import. But if you want to take a stab in repairing we would definitely appreciate this and welcome a PR 😃
