### ISSUE TITLE
check that cplex is functional

### ISSUE THREAD

**Issue by hredestig** [biosustain/optlang#90]
when having cplex in site-packages on py35,36 optlang tries to create a cplex interface but fails and throws exception
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 325, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/travis/build/biosustain/cameo/tests')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 356, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/travis/build/biosustain/cameo/tests/conftest.py')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 362, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/py/_path/local.py", line 650, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 216, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/build/biosustain/cameo/tests/conftest.py", line 3, in <module>
    import cobra.test
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/cobra/__init__.py", line 11, in <module>
    from cobra import design, flux_analysis, io
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/cobra/design/__init__.py", line 5, in <module>
    from cobra.design.design_algorithms import *
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/cobra/design/design_algorithms.py", line 5, in <module>
    from cobra.exceptions import DefunctError
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/cobra/exceptions.py", line 5, in <module>
    import optlang.interface
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/optlang/__init__.py", line 33, in <module>
    from optlang.cplex_interface import Model, Variable, Constraint, Objective
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/optlang/cplex_interface.py", line 118, in <module>
    cplex_status = getattr(cplex.Cplex.solution.status, status_name, None)
AttributeError: module 'cplex' has no attribute 'Cplex'
ERROR: could not load /home/travis/build/biosustain/cameo/tests/conftest.py
```

Better behaviour would be to not make the cplex interface at all

**Comment by KristianJensen** [comment]
I assume this is because cplex is not compatible with py35/36?

**Comment by cdiener** [comment]
@KristianJensen  I have cplex on Python 3.5 and it works fine :smile:

**Comment by KristianJensen** [comment]
@hredestig Do you have an idea why cplex throws an error? When optlang tests which interfaces to load, it generally only excepts ImportError, with the reasoning that if the package (e.g. cplex) is installed in the current environment, the user will want the interface to be loaded and thus any errors should be raised explicitly.

**Comment by long-m-r** [comment]
Wanted to bump this issue. I have cplex 12.7.1.0 installed in python3.5.2 on Ubuntu16.04x64. Annoyingly I get a different error, but either way it is the optlang cplex interface that throws the error.

```
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cplex
>>> import optlang
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matt/fea/.pyenv/lib/python3.5/site-packages/optlang/__init__.py", line 33, in <module>
    from optlang.cplex_interface import Model, Variable, Constraint, Objective
  File "/home/matt/fea/.pyenv/lib/python3.5/site-packages/optlang/cplex_interface.py", line 118, in <module>
    cplex_status = getattr(cplex.Cplex.solution.status, status_name, None)
AttributeError: type object 'Cplex' has no attribute 'solution'
```

**Comment by hredestig** [comment]
The cplex distribution I have is only for <=py3.4 and I think that is also the case for the dist we pull during cameo ci. It's easily worked around by doing the less-than-pretty-fix of just removing the check for <=py3.4 in cplex package. The error I see confuses me a bit but either way, optlang shouldn't throw exception but just proceed with the solvers that work of course.

**Comment by KristianJensen** [comment]
I'm not sure I agree. If a solver is installed but the interface fails, it's a sign that something is wrong. If you have a broken cplex installation shouldn't that either be fixed or removed instead?
I'm generally not a fan of just excepting errors that shouldn't happen...

**Comment by hredestig** [comment]
Yes, at a closer thought I agree, current behaviour is fine, can close this, unless @long-m-r has something more to add?

**Comment by long-m-r** [comment]
Hmm, I agree in principle, but my issue here is that (in my case) the solver installation does in fact work. It's Optlang that is unable to load it (I think the newer cplex python package has changed the API) and because of that, Optlang cannot load at all.

Perhaps it would be better if OptLang throws an error if you try to load a specific solver interface that it couldn't import? In general, I dislike that writing: `from optlang import *` loads all of the solvers and that I am unable to load a specific solver that works when one of them is throwing an error. It should return just the best one that works. If I request 'from optlang.cplex_interface import *' and cplex won't load, that should throw an error. But if I try 'from optlang.glpk_interface import *' and the broken cplex interface stops that from loading, that's a problem with optlang.

**Comment by KristianJensen** [comment]
Cplex 12.7.1 has indeed changed the API slightly causing the above error. I have pushed a fix for this. With IBM's propensity for changing the API, I'm convinced that #91 makes sense, and I'll merge it if you address my comments :)

I'm closing this.
